from enum import Enum
from pydantic import BaseModel, Field, field_validator

class ToneEnum(str, Enum):
    PROFESSIONAL = "Professional"
    FRIENDLSY = "Friendly"
    SHORT_AND_CONCISE = "Short and Concise"


class GenerateReplyRequest(BaseModel):
    email_content: str = Field(
        ...,
        description="The raw content of the received email to reply to.",
        min_length=10,
        max_length=5000,
        examples=["Hi Alex, Could you send over the updated project report by 3 PM today? Thanks, Sarah"]
    )
    tone: ToneEnum = Field(
        ...,
        description="The desired tone of the generated reply.",
        examples=[ToneEnum.PROFESSIONAL]
    )

    @field_validator("email_content", mode="before")
    @classmethod
    def validate_non_whitespace(cls, v: str) -> str:
        if not isinstance(v, str):
            raise ValueError("email_content must be a string")
        trimmed = v.strip()
        if not trimmed:
            raise ValueError("email_content cannot be empty or whitespace-only")
        if len(trimmed) < 10:
            raise ValueError("email_content must contain at least 10 non-whitespace characters")
        if len(trimmed) > 5000:
            raise ValueError("email_content must not exceed 5000 characters")
        return trimmed


class GenerateReplyResponse(BaseModel):
    reply: str = Field(
        ...,
        description="The generated email reply generated by Gemini AI."
    )
    tone: str = Field(
        ...,
        description="The tone used for the reply."
    )
